### ISSUE TITLE
Include Binaries?

### ISSUE THREAD

**Issue by orvisevans** [SnosMe/ooz-wasm#2]
Any chance this could include binaries? (i.e. compiled wasm etc.)
I'm struggling terribly to get this compiled using either locally installed tools or using the Emscripten SDK docker image.

**Comment by SnosMe** [comment]
As said in README .wasm file is base64 embedded using -s SINGLE_FILE=1

I can try to make a second version with separate wasm fie in subdir, but what the advantage of this, can you explain me?

Can't help with building it, CI is pretty easy tho https://github.com/SnosMe/ooz-wasm/blob/master/.github/workflows/ci.yml

**Comment by orvisevans** [comment]
After a few hours working on this, it's making more sense to me. I come from a js background with very little knowledge of C++ (thus wanting to use the wasm). Here's what I learned:

- I needed to install cmake - it didn't come with emscripten SDK
- Compilation was failing to find stdlib.h. I couldn't figure out how to fix that.

To work around this, I went the docker route, running this command from the command line: 
```PowerShell
docker run --rm -it --mount type=bind,source="${PWD}",target="/src" emscripten/emsdk bash -c "cd /src; emcmake cmake -B build; cmake --build build"
```

That compiled it and built it perfectly, though I did have to remove the line `cmake_minimum_required(VERSION 3.15)` from CMakeLists.txt to get it to work since the emscripten cmake version is lower.

**Comment by orvisevans** [comment]
I didn't get that the .wasm file was embedded into the js file (but do now). Thanks for the clarification!

Would you possibly include the ooz.js compiled file in your repo so folks like me can get to it easier?

**Comment by orvisevans** [comment]
One other note that may help others - If running this on a node server, it requires Node 15+ due to ooz's SIMD code.

**Comment by SnosMe** [comment]
You can get supported V8 flags with `node --v8-options`, and one of them is

```
  --experimental-wasm-simd (enable prototype SIMD opcodes for wasm)
        type: bool  default: false
```

It's available in my local Node v12 installation.

About including ooz.js, this is a build artifact, file is minified so absolutely useless to view it in repo, and it's a little bloated due to emscripten. Do you commit "dist" directory where you work? 🙂

**Comment by orvisevans** [comment]
Hmm. I tried --experimental-wasm-simd with node v14.4, and it was giving me errors relating to the simd code. It does work with node v15 though. Not sure why.

Generally no, I don't include the dist folder, true. Plenty of projects do have distribution included rather than making you build from source. That may be appropriate here as a user of this library is likely a js developer like me with very little knowledge on how to build c++ code. Obviously your call though 😄

**Comment by SnosMe** [comment]
Actually strange flag doesn't work on v12, but works on v14 (v14.15.0). Even v8 gives a hint

```
Compiling function #7 failed: invalid value type 'Simd128', enable with --experimental-wasm-simd
```

Distribution is npm package https://www.npmjs.com/package/ooz-wasm 🤷 And if you don't trust in what I've published on npm there is also no trust to ooz.js that I can commit in repo.

**Comment by orvisevans** [comment]
I had not found the npm package. That obviously solves and bypasses this issue. Thanks!
